COMMIT;
Select * FROM AppUser;
Select * FROM Movie;
Select * FROM Genre;
Select * FROM Crew;
Select * FROM MovCharacter;
Select * FROM ProducerType;
Select * FROM Review;
Select * FROM TypeOfMovie;
Select * FROM Stars;
Select * FROM TypeOfProd;
Select * FROM Actor;
Select * FROM Producer;
Select * FROM ScreenWriter;

--Crew--
insert into Crew(FirstName, LastName)values('Gabor','Csupo');
insert into Crew(FirstName, LastName)values('Jeff','Stockwell');
insert into Crew(FirstName, LastName)values('David','Paterson');
insert into Crew(FirstName, LastName)values('Katherine','Paterson');
insert into Crew(FirstName, LastName)values('Josh','Hutcherson');
insert into Crew(FirstName, LastName)values('Anna-Sophia','Robb');
insert into Crew(FirstName, LastName)values('Zooey','Deschanel');
insert into Crew(FirstName, LastName)values('Robert','Patrick');
insert into Crew(FirstName, LastName)values('Bailee','Madison');
insert into Crew(FirstName, LastName)values('Kate','Butler');
insert into Crew(FirstName, LastName)values('Devon','Wood');
insert into Crew(FirstName, LastName)values('Emma','Fenton');
insert into Crew(FirstName, LastName)values('Grace','Brannigan');
insert into Crew(FirstName, LastName)values('Latham','Gaines');
insert into Crew(FirstName, LastName)values('Judy','McIntosh');
insert into Crew(FirstName, LastName)values('Patricia','Aldersley');
insert into Crew(FirstName, LastName)values('Lauren','Clinton');
insert into Crew(FirstName, LastName)values('Isabelle-Rose','Kircher');
insert into Crew(FirstName, LastName)values('Cameron','Wakefield');
insert into Crew(FirstName, LastName)values('Elliot','Lawless');
insert into Crew(FirstName, LastName)values('Carly','Owen');
insert into Crew(FirstName, LastName)values('Jen','Wolfe');
insert into Crew(FirstName, LastName)values('James','Gaylyn');
insert into Crew(FirstName, LastName)values('Ian','Harcourt');
insert into Crew(FirstName, LastName)values('Brandon','Cook');
insert into Crew(FirstName, LastName)values('Tyler','Atfield');
insert into Crew(FirstName, LastName)values('Maisy','McLeod-Riera');
insert into Crew(FirstName, LastName)values('Hudson','Mills');
insert into Crew(FirstName, LastName)values('Matt','Gibbons');
insert into Crew(FirstName, LastName)values('Phil','Grieve');
insert into Crew(FirstName, LastName)values('Fernado','Gonzalez');
insert into Crew(FirstName, LastName)values('Mikaila','Baumel');
insert into Crew(FirstName, LastName)values('Aaron','Beard');
insert into Crew(FirstName, LastName)values('Luke','Burnyeat');
insert into Crew(FirstName, LastName)values('Zoe','Cramond');
insert into Crew(FirstName, LastName)values('Dwight','Wilson II');
insert into Crew(FirstName, LastName)values('Shelby','Young');
insert into Crew(FirstName, LastName)values('Tim','Coddinton');
insert into Crew(FirstName, LastName)values('Micheal','Flaherty');
insert into Crew(FirstName, LastName)values('Kevin','Halloran');
insert into Crew(FirstName, LastName)values('Lauren', 'Levine');
insert into Crew(FirstName, LastName)values('David','Kaufmann');
insert into Crew(FirstName, LastName)values('Hal','Lieberman');
insert into Crew(FirstName, LastName)values('David','Paterson');
insert into Crew(FirstName, LastName)values('Alex','Schwartz');
insert into Crew(FirstName, LastName)values('Meyer','Chwarzstein');
insert into Crew(FirstName, LastName)values('Brigham','Taylor');

--Stars--
insert into Stars values(41,7);
insert into Stars values(42,7);
insert into Stars values(43,7);
insert into Stars values(44,7);
insert into Stars values(45,7);
insert into Stars values(46,7);
insert into Stars values(47,7);
insert into Stars values(48,7);
insert into Stars values(49,7);
insert into Stars values(50,7);
insert into Stars values(51,7);
insert into Stars values(52,7);
insert into Stars values(53,7);
insert into Stars values(54,7);
insert into Stars values(55,7);
insert into Stars values(56,7);
insert into Stars values(57,7);
insert into Stars values(58,7);
insert into Stars values(59,7);
insert into Stars values(60,7);
insert into Stars values(61,7);
insert into Stars values(62,7);
insert into Stars values(63,7);
insert into Stars values(64,7);
insert into Stars values(65,7);
insert into Stars values(66,7);
insert into Stars values(67,7);
insert into Stars values(68,7);
insert into Stars values(69,7);
insert into Stars values(70,7);
insert into Stars values(71,7);
insert into Stars values(72,7);
insert into Stars values(33,7);
insert into Stars values(74,7);
insert into Stars values(75,7);
insert into Stars values(76,7);
insert into Stars values(77,7);
insert into Stars values(78,7);
insert into Stars values(79,7);
insert into Stars values(80,7);
insert into Stars values(81,7);
insert into Stars values(82,7);
insert into Stars values(83,7);
insert into Stars values(84,7);
insert into Stars values(85,7);
insert into Stars values(86,7);
insert into Stars values(87,7);

--Screen Writer--
insert into ScreenWriter values(42);
insert into ScreenWriter values(43);
insert into ScreenWriter values(44);

--Producer--
insert into Producer values(41);
insert into Producer values(78);
insert into Producer values(79);
insert into Producer values(80);
insert into Producer values(81);
insert into Producer values(82);
insert into Producer values(83);
insert into Producer values(84);
insert into Producer values(85);
insert into Producer values(86);
insert into Producer values(87);

--Type of Producer--
insert into TypeOfProd(Crew_Id, Pname) values(41,'Director');
insert into TypeOfProd(Crew_Id, Pname) values(78,'co-Producer');
insert into TypeOfProd(Crew_Id, Pname) values(79,'Procution Executive');
insert into TypeOfProd(Crew_Id, Pname) values(80,'co-Producer');
insert into TypeOfProd(Crew_Id, Pname) values(81,'Associate Producer');
insert into TypeOfProd(Crew_Id, Pname) values(82,'Producer');
insert into TypeOfProd(Crew_Id, Pname) values(83,'Producer');
insert into TypeOfProd(Crew_Id, Pname) values(84,'Producer');
insert into TypeOfProd(Crew_Id, Pname) values(85,'Executive Producer');
insert into TypeOfProd(Crew_Id, Pname) values(86,'co-Producer');
insert into TypeOfProd(Crew_Id, Pname) values(87,'Production Exectuive');

--Producer Type--
insert into ProducerType values ('Production Exectuive', 'A Production Executive oversees and directs production operations for a manufacturing organization. They lead production operations, coordinate production staff and equipment, and ensure the quality and profitability of products.');
insert into ProducerType values ('Associate Producer', 'an Associate Producer generally assists the producer in putting the TV program or film together. Duties may include writing, editing, organizing scripts, running the teleprompter in news casts, or helping the editor by making beat calls.');

--Actor--
insert into Actor values(45);
insert into Actor values(46);
insert into Actor values(47);
insert into Actor values(48);
insert into Actor values(49);
insert into Actor values(50);
insert into Actor values(51);
insert into Actor values(52);
insert into Actor values(53);
insert into Actor values(54);
insert into Actor values(55);
insert into Actor values(56);
insert into Actor values(57);
insert into Actor values(58);
insert into Actor values(59);
insert into Actor values(60);
insert into Actor values(61);
insert into Actor values(62);
insert into Actor values(63);
insert into Actor values(64);
insert into Actor values(65);
insert into Actor values(66);
insert into Actor values(67);
insert into Actor values(68);
insert into Actor values(69);
insert into Actor values(70);
insert into Actor values(71);
insert into Actor values(72);
insert into Actor values(73);
insert into Actor values(74);
insert into Actor values(75);
insert into Actor values(76);
insert into Actor values(77);

--MovCharacter--
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Jess Aarons','Jess Aarons is the protagonist of Bridge to Terabithia.', 45);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Leslie Burke','Leslie Burke is the deuteragonist of Bridge to Terabithia. She is Jess Aarons best friend and possible love interest.', 46);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Ms. Edmunds','Ms. Edmunds is a music teacher at Jesse''s school. She seemed to make her lessons fun and exciting. Her class enjoyed them a lot.', 47);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Jack Aarons','Jess''s father', 48);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('May Belle Aarons','May Belle Aarons is a character from Bridge to Terabithia. She is one of Jess Aarons'' younger sisters.', 49);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Mary Aarons', null, 50);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Brenda Aarons', null, 51);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Ellie Aarons', null, 52);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Joyce Aarons', null, 53);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Bill Burke', null, 54);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Judy Burke', null, 55);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Granda Burke', null, 56);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Janice Avery', null, 57);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Carla', null, 58);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Scott Hoager', null, 59);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Gary Fulcher', null, 60);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Madison', null, 61);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Mrs. Myers', null, 62);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Principal Turner', null, 63);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Kenny', null, 64);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('First Grade Boy', null, 65);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Eigth Grade Boy', null, 66);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('First Grade Girl', null, 67);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Willard Hughes', null, 68);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Dark Master', null, 69);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Mr. Bailey', null, 70);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Classmate', null, 71);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Little girl', null, 72);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Art Gallery', null, 73);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('School Kid', null, 74);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Parishioner', null, 75);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('P.E. Teacher', null, 76);
insert into MovCharacter (Char_Name, Char_Desc, Crew_Id) values('Ellie Aarons', null, 77);
